### ISSUE TITLE
Support plugin for ASCII-art packet headers

### ISSUE THREAD

**Issue by larseggert** [cabo/kramdown-rfc#132]
https://github.com/luismartingarcia/protocol

**Comment by cabo** [comment]
1.5.11:
```
~~~ protocol
Source:16
Reserved:40
TTL:8
~~~
``` 
generates just the ASCII art (and shows that in TXT and HTML).

```
~~~ protocol-goat
Source:16
Reserved:40
TTL:8
~~~
```
also sends the output of "protocol" through goat for SVG.

The input is joined together with commas to feed the command line.
Holler if you need a way to specify options.

As usual for authoring tools, a tool "protocol" needs to be on the path.

Enjoy, feedback welcome.

**Comment by larseggert** [comment]
I see 1.5.11 on rubygems but not on GitHub?
