### ISSUE TITLE
generating bitfield/bytefield tables

### ISSUE THREAD

**Issue by dkg** [cabo/kramdown-rfc#151]
it can be quite useful for a standard to include a bitfield/bytefield representation of a protocol data object.

For example, [RFC 1035 §4.1.1](https://datatracker.ietf.org/doc/html/rfc1035#section-4.1.1) contains:

```
                                    1  1  1  1  1  1
      0  1  2  3  4  5  6  7  8  9  0  1  2  3  4  5
    +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
    |                      ID                       |
    +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
    |QR|   Opcode  |AA|TC|RD|RA|   Z    |   RCODE   |
    +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
    |                    QDCOUNT                    |
    +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
    |                    ANCOUNT                    |
    +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
    |                    NSCOUNT                    |
    +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
    |                    ARCOUNT                    |
    +--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+--+
```

It would be great to be able to generate tables like this that would at least use colspan attributes (which are [supported in xml2rfc v3](https://datatracker.ietf.org/doc/html/rfc7991#section-2.56.3)).

I'm aware that most markdown variants don't support colspan (multimarkdown [seems to be the exception](https://fletcher.github.io/MultiMarkdown-4/tables).

It's also conceivable that we'd want rowspan attributes for larger blocks, but colspan seems like the most likely thing here.

**Comment by cabo** [comment]
This assumes tables are a good way to represent box notation.
kramdown-rfc provides support for the tool protocol to generate box notation as traditional ASCII art, and for goat to convert this into an equally-spaced SVG figure.
I'm afraid this isn't fully documented yet, but see https://github.com/cabo/kramdown-rfc2629/wiki/SVG#goat for goat.

Separately: Yes, we need a good way to represent rowspans and colspans in tables.
Unfortunately, the upstream (kramdown) table syntax does not provide that yet.
https://github.com/gettalong/kramdown/issues/87 shows work that we could pick up.
This is on the agenda, just not very high up at the moment...

**Comment by cabo** [comment]
Try

```
~~~ protocol-goat
Source:16
Reserved:40
TTL:8
~~~
```

or 

```
~~~ protocol-aasvg
Source:16
Reserved:40
TTL:8
~~~
```

until we have that documented.
(aasvg is a goat replacement with better fine positioning.)

**Comment by dkg** [comment]
Thanks, i really like the looks of aasvg, but it's unclear to me where i should get the `protocol` tool.  it looks like it is a command line tool that acts as a stdin/stdout filter, and it was added in 1c57f8fb.  What tool is this?

**Comment by cabo** [comment]
I now have added a bit of documentation at https://github.com/cabo/kramdown-rfc2629/wiki/SVG#protocol

Please feel free to add information there or ask further questions.

**Comment by dkg** [comment]
Thanks for this additional documentation, @cabo.  This is what i needed.
