### ISSUE TITLE
smart_quotes: no

### ISSUE THREAD

**Issue by martinthomson** [cabo/kramdown-rfc#157]
Please consider a default (with the v: 3 change perhaps) to disable the use of smart quotes.

Typographically, this is good.  In practice, this just causes churn when xml2rfc reverts them all.

**Comment by cabo** [comment]
Hmm,

I sure hope we'll get typographically sane documents out of xml2rfc at some point.
While we have the current unsatisfactory situation,

```
  suppress_typography = ascii_target || $options.v3
```

This has been in the v3 mode implementation for a long time (refactoring makes it too much work right now to find out when exactly).
Do you have a counterexample where typographical quotes are still generated with --v3?

(Maybe you haven't been setting v3 mode -- one more reason why I want to make this the default now.)

**Comment by martinthomson** [comment]
No counterexample, but I was looking to perform some cleanup of stuff I added to a template.  I should have tested it.
