### ISSUE TITLE
refxml.rb failing in handle_name with "undefined method `split' for nil:NilClass (NoMethodError)"

### ISSUE THREAD

**Issue by guyharris** [cabo/kramdown-rfc#163]
We're using kramdown-rfc2629-1.6.2 to build HTML and text versions of some I-Ds written in Markdown, at https://github.com/pcapng/pcapng.

It's failing with

```
/usr/lib/ruby/gems/3.0.0/gems/kramdown-rfc2629-1.6.2/lib/kramdown-rfc/refxml.rb:105:in `handle_ins': undefined method `split' for nil:NilClass (NoMethodError)
[36](https://github.com/pcapng/pcapng/runs/5431754474?check_suite_focus=true#step:6:36)
	from /usr/lib/ruby/gems/3.0.0/gems/kramdown-rfc2629-1.6.2/lib/kramdown-rfc/refxml.rb:145:in `authorps_from_hash'
```

with a log for such a failure at https://github.com/pcapng/pcapng/runs/5431754474?check_suite_focus=true (if that run log hasn't been removed by GitHub yet).

I get similar failures on macOS Big Sur with kramdown-rfc2629-1.6.3; I can make the failures go away by wrapping tests around some calls to `split`:

```
105,111c105,113
<       parts[-1..-1] = parts[-1].split
<       s = if surname = aups.rest[surname_k]
<             surname.split
<           else parts.reverse.take_while{|x| !looks_like_initial(x)}.reverse
<           end
<       aups.rest[initials_k] = initials_from_parts_and_surname(aups, parts, s)
<       aups.rest[surname_k] = s.join(" ")
---
>       if parts[-1..-1]
>         parts[-1..-1] = parts[-1].split
>         s = if surname = aups.rest[surname_k]
>               surname.split
>             else parts.reverse.take_while{|x| !looks_like_initial(x)}.reverse
>             end
>         aups.rest[initials_k] = initials_from_parts_and_surname(aups, parts, s)
>         aups.rest[surname_k] = s.join(" ")
>       end
129,131c131,135
<       s = surname.split
<       aups.rest[initials_k] ||= initials_from_parts_and_surname(aups, parts, s)
<       aups.rest[surname_k] = s.join(" ")
---
>       if surname
>         s = surname.split
>         aups.rest[initials_k] ||= initials_from_parts_and_surname(aups, parts, s)
>         aups.rest[surname_k] = s.join(" ")
>       end
```

but presumably there is a reason never to expect that the values being split will never be `nil`.

If this is a problem with our Markdown, this should probably be made to fail with an error message indicating what needs to be fixed in our documents rather than a language-level failure.

If this is a mismatch between the installed version of kramdown-rfc2629 and either the installed version of Ruby or the installed version of some other gem, is there some way to determine what versions are mismatched?

**Comment by cabo** [comment]
See workaround (by more correct YAML) in https://github.com/pcapng/pcapng/pull/112

**Comment by guyharris** [comment]
I.e., this is a problem with our Markdown, but it's also the case that kramdown-rfc isn't handling it as well as it should hence "workaround")?

**Comment by cabo** [comment]
Yes.  There is no point in setting ins: to an empty string, so that was never tested.
Removing the entire parameter solves this (my PR also removes the empty string on name:).
So my workaround is also your fix -- just pull the PR...
(And I'm now fixing the code.)
