### ISSUE TITLE
Triple-brace contact over multiple lines

### ISSUE THREAD

**Issue by martinthomson** [cabo/kramdown-rfc#171]
Let's say that I reflow the original text and it ends up looking like this:

```md
of people including {{{Bernard Aboba}}}, {{{Brian Carpenter}}}, {{{Stuart
Cheshire}}}, {{{Mark Nottingham}}}, {{{Russ Housley}}}, {{{David Schinazi}}},
```

For some reason, this end up producing a reference to "_Stuart_Cheshire" rather than a `<contact>` element.

**Comment by cabo** [comment]
Not sure if allowing just one newline is right; just trying to avoid runaway captures.

**Comment by martinthomson** [comment]
Thanks Carsten.  I can't imagine someone needing 3 lines for a name, so this is probably OK.

**Comment by cabo** [comment]
When "Queen Victoria I, Queen of the United Kingdom, Empress of India, Queen Canada, Queen of Australia, Queen of New Zealand, Head of the Commonwealth" lines up, we can revisit this...
