### ISSUE TITLE
Subscribe at info added for venue can be wrong

### ISSUE THREAD

**Issue by martinthomson** [cabo/kramdown-rfc#176]
When the `venue` block contains a mailing list, text like the following is added:

> Subscribe at https://www.ietf.org/mailman/listinfo/ohai/.

This generally works because most mailing lists follow a distinct pattern.  But that pattern is limited to IAB, IETF, and IRTF lists.

The HTTP WG has a list that is not hosted by the IETF, but the following text is still added:

> Subscribe at https://www.ietf.org/mailman/listinfo/ietf-http-wg/.

This link is bad.  For this group, instructions on how to subscribe can be found on the archive link.  The right answer here is probably to have a list of `['@ietf.org', '@iab.org', '@irtf.org']` and check for that suffix before adding the subscribe link.

**Comment by cabo** [comment]
Right, this was inadvertently a non-backwards-compatible change, sorry about putting this out together with the 1.6.15 emergency fix.
But this is now similar to the processing we already had for the archive link, which has an "arch" parameter in the YAML; you now need to add a "subscribe" parameter...
Checking the mail domain makes sense; I'll devise a fix (but I also think setting the "subscribe" parameter in the document would make sense as well.)
