### ISSUE TITLE
kramdown-rfc version 1.6.17 is not published on rubygems

### ISSUE THREAD

**Issue by kesara** [cabo/kramdown-rfc#178]
kramdown-rfc version 1.6.17 is not available on [rubygems.org](https://rubygems.org/gems/kramdown-rfc).

**Comment by cabo** [comment]
Thanks!  Fixed.

**Comment by kesara** [comment]
@cabo, the latest version 1.6.19 is not published on rubygems yet. https://rubygems.org/gems/kramdown-rfc

**Comment by cabo** [comment]
Thank you, that is now fixed.
(I got stuck doing 1.6.20 and forgot to push .19.)
