### ISSUE TITLE
Footnote references in definition list labels blow up...

### ISSUE THREAD

**Issue by cabo** [cabo/kramdown-rfc#18]
...because the latter are attributes in XML2RFCv2.

**Comment by miekg** [comment]
Same is true of having references to other sections in there

**Comment by cabo** [comment]
Yep.  This will be really fixable only in XML2RFCv3; this issue was more about avoiding the error by doing some half-adequate workaround, as we have e.g. in table headings.

**Comment by cabo** [comment]
This was actually fixed for v3 in 1.3.18 (commit 2298e53).
