### ISSUE TITLE
svgcheck removed -X

### ISSUE THREAD

**Issue by snorp** [cabo/kramdown-rfc#187]
This seems to break, amongst other things, svg generation in martinthomson/i-d-template

**Comment by cabo** [comment]
In https://github.com/ietf-tools/svgcheck/pull/32, Kesara said he was going to fix this.
If he doesn't, I can fix it here, of course.

**Comment by snorp** [comment]
Oh, hmm. I do not get the warning for `-X` in `0.7.1`, but the generation still fails. `0.6.2` works. See https://github.com/martinthomson/i-d-template/issues/364#issuecomment-1440468814

**Comment by cabo** [comment]
svgcheck seems to have lost the ability to read from stdin.

**Comment by snorp** [comment]
Seems likely to be caused by this change: https://github.com/ietf-tools/svgcheck/commit/ac1cc516f29da1495dfa10e4cfed0b7f720363be#diff-ce7bd9cc13feace43ecfdaaa297442628841e2f13939fd19d986adff269031bb

**Comment by cabo** [comment]
fixed in 1.6.24

**Comment by snorp** [comment]
Yup, confirmed that works.
