### ISSUE TITLE
XHTML reference causes problems

### ISSUE THREAD

**Issue by mnot** [cabo/kramdown-rfc#19]
W3C.REC-xhtml-basic-20080729

...causes invalid XML output, due to the title.

**Comment by cabo** [comment]
Interesting.  Of course the include processing here assumes that the XML imported is valid.
The desire to have US-ASCII only XML will create some problems here.
But here, the source is not even UTF-8 (looks like the usual "misinterpret UTF-8 as a sequence of bytes each representing a UCS-1 code point and represent the resulting Unicode as UTF-8 while losing a few of the bytes" problem).
Need to find out who maintains that collection.

**Comment by cabo** [comment]
(Workaround is to not use `coding: us-ascii`, as xml2rfc will scrub the input then.)

**Comment by cabo** [comment]
It seems this is now fixed in https://bib.ietf.org/public/rfc/bibxml4/reference.W3C.REC-xhtml-basic-20080729.xml
(It is now more practical to assume that the reference source, bib.ietf.org, provides valid XML.)
