### ISSUE TITLE
Markdown draft with unmodified author info now failing address normalization

### ISSUE THREAD

**Issue by SpencerDawkins** [cabo/kramdown-rfc#198]
I might be reporting this in the wrong place, but somewhere between kramdown-rfc and xml2rfc, I'm suddenly getting this error

> Traceback (most recent call last):
>   File "/mnt/c/users/sdawkins/documents/github/draft-gruessing-moq-requirements/lib/.venv/lib/python3.8/site-packages/xml2rfc/util/postal.py", line 189, in get_normalized_address_info
>     i18naddress.normalize_address(adr)

The draft in question has this as the author info

> author:
>   -
>     ins: J. Gruessing
>     name: James Gruessing
>     organization: Nederlandse Publieke Omroep
>     country: Netherlands
>     email: james.ietf@gmail.com
>   -
>     ins: S. Dawkins
>     name: Spencer Dawkins
>     organization: Tencent America LLC
>     country: United States of America
>     email: spencerdawkins.ietf@gmail.com

The error automagically goes away when I delete the country: attributes and attempt to make the result. 

I happened to delete my local repo copy and re-cloned our repo from Github.com, which caused all of https://github.com/martinthomson/i-d-template to be rebuilt, so I suspect that something changed in the past couple of weeks, but don't understand the tool chain well enough to spot obvious changes that might cause the problem.

**Comment by cabo** [comment]
https://github.com/ietf-tools/xml2rfc/issues/997
Already fixed in
https://github.com/ietf-tools/xml2rfc/pull/998

I hope we’ll get a release very soon…

Grüße, Carsten

**Comment by cabo** [comment]
(The country is called "The Netherlands", BTW...)

**Comment by SpencerDawkins** [comment]
@cabo, you're the best!

Spencer

**Comment by cabo** [comment]
Should be fixed now:
https://github.com/ietf-tools/xml2rfc/releases/tag/v3.17.3

**Comment by cabo** [comment]
This seems to be completed -- closing this.
