### ISSUE TITLE
Opening links in a new window

### ISSUE THREAD

**Issue by paulehoffman** [cabo/kramdown-rfc#202]
Kramdown apparently supports marking a link to open in a new window with `{:target="_blank"}`, such as:

```A repository for this draft can be found [here](https://github.com/paulehoffman/7997bis){:target="_blank"}.```

In kramdown-rfc 1.6.39, the XML does not seem to reflect that.

**Comment by cabo** [comment]
How would the XML look like?  I'm not aware of a feature in RFCXML that would allow specifying a new window with a link (xref).

**Comment by paulehoffman** [comment]
Arrrrgh, good point. This would need to wait for an update to our XML spec to handle this.
