### ISSUE TITLE
Why not "tt" for code spans?

### ISSUE THREAD

**Issue by yaronf** [cabo/kramdown-rfc#218]
The xml2rfc syntax for code spans is `<tt>some text</tt>`. But kdrfc converts backtick-surrounded text to `<spanx style="verb">some text</spanx>`. The outcome is HTML that's looking good, but no indication of the code span in the `.txt` output file. This is different from the usual behavior of xml2rfc which surrounds the text in double quotes when rendering to plaintext. Also, it appears that the RFC Editor converts the `spanx` tags into `tt` during the publication process.

Code reference: [https://github.com/cabo/kramdown-rfc/blob/367553a4f2994ca167e8e659ffb92e74febe76a0/lib/kramdown-rfc2629.rb#L1347](https://github.com/cabo/kramdown-rfc/blob/367553a4f2994ca167e8e659ffb92e74febe76a0/lib/kramdown-rfc2629.rb#L1347)

**Comment by cabo** [comment]
Hi Yaron,

xml2rfc converts `<spanx style="verb"` into `<tt` automatically.  The behavior is exactly the same.
xml2rfc was deliberately changed to stop indicating <tt markup in plaintext with xml2rfc 3.11.0 (see [1], [2] and the discussion around that).

Until rfcxml is changed to support <tt rendering again in some way, there is no way for kramdown-rfc to generate XML that can be rendered properly in both plaintext and HTML/PDF.  Of course, a workaround could be defined (which would require adding noise to HTML/PDF).  If you can describe your use case, maybe I can form an opinion which workaround that should be.

[1]: <https://mailarchive.ietf.org/arch/msg/rfc-markdown/sJhKqGSnSyG85JcV_gXKvgT_uII>
[2]: <https://mailarchive.ietf.org/arch/msg/rfc-markdown/7JCbdtG8xISqHMdmJmAoXPn0EhM>

**Comment by yaronf** [comment]
Hi Carsten,

Thank you for bringing me into the sausage making. I would still say that `kdrfc` had better produce "canonical" XML (i.e., `tt`), but I agree that's mostly a theoretical discussion.

For background, the use case is this: https://github.com/yaronf/xmlrfc2md (very much work-in-progress).

Thanks!
