### ISSUE TITLE
Error 65

### ISSUE THREAD

**Issue by paulehoffman** [cabo/kramdown-rfc#220]
If I put XML-stlye comments in the first section, the error message is just "Error 65" instead of "You can't have comments in the first section; maybe move them to the 'abstract' section".

**Comment by cabo** [comment]
Can you give an example input file plus the commandline that you used?

Depending in where the xml-style comemnt occurred, I get something like:

```
*** YAML syntax error: (<unknown>): could not find expected ':' while scanning a simple key at line 14 column 1
*** kramdown-rfc failed, status 65
``` 

I do not get "Error 65", and I do get a useful error message as well.

**Comment by paulehoffman** [comment]
After the last informative reference, just before the abstract.
```
informative:
  RFC8118:

<!--
This
-->
--- abstract
```

`make: *** [draft-hoffman-rfc7995bis.xml] Error 65`

**Comment by cabo** [comment]
Your example generates

```
*** YAML syntax error: (<unknown>): could not find expected ':' while scanning a simple key at line 39 column 1
*** kramdown-rfc failed, status 65
```

for me.

Can you say more about the context that appears to swallow the error message?

**Comment by cabo** [comment]
XML comments are not comments in the YAML header.
Of course, there is nothing wrong with including text that looks like an XML comment in the YAML header, and this could be a normal thing in markdown-syntax fields such as `ann`.
The error message seems to have vanished into /tmp/kram-errors.txt according to your command line.

**Comment by paulehoffman** [comment]
Indeed it did, but that is still not a great error message for the issue at hand. I fully agree that "XML comments are not comments in the YAML header"; what I'm hoping for is that the program would see them and say "don't put them there".

**Comment by cabo** [comment]
Well, since kramdown-rfc does not parse the YAML header as XML, it is blissfully unaware of passages that would be XML comments in an XML document.  Since, as I said, XML comments can be valid content in an entry of the YAML header, adding some hack to recognize this as a foreign language and warn about it would be counterproductive.  So I don't think anything can be done about this.

**Comment by paulehoffman** [comment]
OK, understood. I had hoped there could be an initial pass looking for misplaced comments, but I see what you mean that they could be valid content in some edge cases.
