### ISSUE TITLE
Plain Line Breaks?

### ISSUE THREAD

**Issue by CxRes** [cabo/kramdown-rfc#222]
I am trying to achieve (I don't know of another way to semantically separate (or break continuity) between two separate paragraphs within the same section within rfcxml's restrictions):

```
<t>Some text</t>
<br>
<t>More text</t>
```

It seems I cannot do this because the break gets included in the previous paragraph or gets wrapped in its own paragraph.

The closest I have achieved is:
```
Some text\\
{{&zwsp}}

More text
```

which gives me:
```
<t>Some text<br>
</t>                       
<t>More text</t>
```

What am I missing here?

**Comment by cabo** [comment]
Hi Rahul,

I have trouble imagining what you are trying to achieve -- "semantically separate (or break continuity)"?
If you can give us a peak on the document maybe it's easier to understand for us.

**Comment by CxRes** [comment]
Hi Carsten,

I-D template has been acting strange which prevents me from putting up the compiled output for my example (which literally is an example), even Martin seems to agree that behaviour is strange. Give me a day or two (I might just fork the repo when I get my WSL machine back) to give you an actual sample text. 

Meanwhile, let me try to explain what I am doing as best as I can. Sometimes one like to show a semantic separation between two paragraphs, as they are taking about slightly distinct things (in my case, an HTTP request and a corresponding HTTP response), but keep them within the same section. Sometimes this is done by adding extra vertical space between paragraphs, sometimes a separator or in older books even drop caps. I wanted to mimic the first of the three, adding extra vertical space  between request and response text (since this would become two linebreaks in the txt version), which I do as follows:

```md
request text

\\
response text
```

But this unsatisfactorily produces:
```xml
<t>request text</t>
<t><br>
response text</t>
```

What I would like to see, at the very least is: 
```
<t>request text</t>
<br>
<t>response text</t>
```

I also tried:
```md
request text

<br/>

response text
```

which turns into the pointless:
```
<t>request text</t>
<t><br></t>
<t>response text</t>
```

I am, of course, open to suggestion if there are better ideas for organizing text.

**Comment by CxRes** [comment]
Unnumbered section sounds better, but it did not occur to me to use it.

Thanks for the suggestion, Carsten!

**Comment by CxRes** [comment]
I've tried playing around with unnumbered sections, but I am not sure how to create an unnumbered section without a title! It seems the `{:unnumbered}` ALD is tied to the title of a section. Do I use raw XML here? Or is there another way? 

Please Help!!!

**Comment by cabo** [comment]
I use unnumbered sections *with* a title.
While the v3 grammar does allow sections without titles (neither title= attribute nor <name child), I don't think they are actually meant to be used this way (the rendering seems to ignore the presence of the unnamed subsection).

**Comment by CxRes** [comment]
I played around with this a bit and here are my results:

The rendering engine does complain of a missing `<name` tag, which is a bug either in the renderers or the spec. However, it allows `<section><name/>` without any issues, and this produces the desired HTML and TXT. (I did not check `title=`, as that is deprecated anyway).

As far as kramdown-rfc is concerned, I managed to recreate it in the most obtuse way possible. I define a "nothing" entity as:
```yaml
entity:
  nothing: ""
```

Then my untitled unnumbered section looks like this:
```md
### {{&nothing}}
{{: anchor="unique" numbered="false" toc="exclude"}}
```

This feels so horribly hacky though.... I wonder if there is a better way?
