### ISSUE TITLE
Order of autogenerated references

### ISSUE THREAD

**Issue by dkg** [cabo/kramdown-rfc#225]
Currently, auto-generated references (those derived from inline data in the text, like RFCs or DOI identifiers) appear in the References section in the order in which they first appear in the document.

I've received [requests to order references alphabetically](https://gitlab.com/dkg/e2e-mail-guidance/-/issues/11) for multiple documents lately (also for draft-ietf-dprive-unilateral-probing).  Is there a way to ask kramdown-rfc to order the references in numerical order rather than document order, or do i need to make a manual listing in the references section?

**Comment by cabo** [comment]
xml2rfc does that for you, as per "sortrefs".
RFCXML has an indefensible default for this: no.
Set it to yes in pi:, or let

v: 3

do this and a few other useful things for you.

**Comment by dkg** [comment]
huh, interesting.  i was passing `--v3`  to `kramdown-rfc` on the command line, and i didn't know that `v: 3` in the metadata block would do this additional behavior.  Should `kramdown-rfc --v3` also explicitly set this to "yes"?

**Comment by cabo** [comment]
Maybe calling it "v: 3" was confusing, as this ist mostly a package of settings that you want to do for v3 but that cannot be default for backwards compatibility reasons.  (--v3 has been default since 2022-02-22T22:02:22.)

**Comment by cabo** [comment]
Well, DRY is fine, but supporting dusty decks is fine, too (and v: 3 is a declaration that you aren't a dusty deck).

v: 3 mostly does three things right now:

      ps.default!(:stand_alone, true)
      ps.default!(:ipr, "trust200902")
      ps.default!(:pi,  {"toc" => true, "sortrefs" => true, "symrefs" => true})

So you can get rid of all three poeces of boilerplte in exchange for putting in one, easy to remember on.

**Comment by dkg** [comment]
good call.  I've done that now, which reduced my boilerplate.  thanks :)
