### ISSUE TITLE
Fails on a simple .md with unintelligible error message

### ISSUE THREAD

**Issue by mouse07410** [cabo/kramdown-rfc#229]
MacOS Sonoma 14.4.1, Ruby-3.3.0, Python-3.12.3, current stable `kramdown-rfc` installed via `gem install krandown-rfc`.

```sh
$ $ kramdown-rfc -V
kramdown-rfc 1.7.11
$ kramdown-rfc -v -3 draft-uri-lamps-pquake.md
*** v2 nil v3 true
*** YAML syntax error: (<unknown>): did not find expected key while parsing a block mapping at line 4 column 1
$ head -10 draft-uri-lamps-pquake.md
---

title: "PQuAKE - Post-Quantum Authenticated Key Exchange"
abbrev: "PQuAKE"
category: info

docname: draft-uri-lamps-pquake-latest
submissiontype: IETF  # also: "independent", "IAB", or "IRTF"
number: 00
date: 2024-04-18
```

It is unclear what key it expected, nor what it thought it did find. Also, verbosity of the output does leave something to be desired.

Please help if you can.

**Comment by cabo** [comment]
Can you put in the actual .md file (or mail it to me)?  Not sure that `head -10` and the copy/paste preserves any character weirdness that may be present.

**Comment by mouse07410** [comment]
When I saw your post, I double-checked the beginning of my file, and noticed that next line after the `author:` key had a space before `-`, like
```yaml
author:
 -
    name: Whoever
```
instead of
```yaml
author:
-
    name: Whoever
```

After taking care of that, the file became compile-able again. Thank you!

P.S. Is there a list of _all_ the keys that `kramdown-rfc` accepts? I.e., i I want to add mailing address - how can I do it?

**Comment by cabo** [comment]
Author info is documented here (as well as on the README.md):

https://github.com/cabo/kramdown-rfc/wiki/Syntax2#authors-contributors

> P.S. Is there a list of all the keys that kramdown-rfc accepts? I.e., i I want to add mailing address - how can I do it?

See above.  The YAML mostly reflects the RFCXML vocabulary, which also has an element for email:

https://authors.ietf.org/rfcxml-vocabulary#email
