### ISSUE TITLE
Validating examples

### ISSUE THREAD

**Issue by mnot** [cabo/kramdown-rfc#70]
Just a thought - it would be really nice if kramdown-rfc2629 could automatically extract example sections denoted with `~~~` and dispatch them to validators of various sorts (likely based upon the language declared for that block).

Is such a thing possible? I'm looking to validated [structured field values](https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html), but I can imagine many other uses...

**Comment by cabo** [comment]
Yes.  I'm wondering how to do this in a way that doesn't require kramdown-rfc to know about all processors and validators, and doesn't open up every kramdown-rfc user to a remote arbitrary code execution vulnerability.  So basically, I'm thinking about a YAML header like:

~~~
codeblocks:
  goat:
    process:
      - execute:
          input: block
          output: temp
          command: goat $input
      - execute:
          input: temp
          output: artset
          command: svgcheck -qa
      - artset:
          svg: output
          ascii-art: input
    validate: no
~~~

Probably, this will require users to maintain a config file that collects kosher processors/validators.
Hmm.

**Comment by mnot** [comment]
That could work (if a _little_ bit high-friction).

I think I need it to, upon encountering a code block:
  - Look at the language declaration and see if it's configured for validation / handling
  - If so, call the configured program
  - If the program returns 0, it's valid
  - Otherwise, it's invalid; abort processing and give an error to the user (conveying the context where it happened, and anything the program gives you back on stdout

It would also be _very_ good to allow an individual code block to pass arguments to the program, to avoid the necessity of configuring multiple `codeblocks` for different forms. I ask for this because Structured Fields requires you to know the type of field (dictionary, list or item) to parse. 

If that's hard to do with the kramdown syntax, maybe define a `code block` as a prefix, and pass anything after `_` to the program as an arg, so we can use something like `structured-header_dictionary`?

For future development, it might be interesting to allow such programs to be used as formatters too; i.e., if the result is 0, replace the code block with stdout.

**Comment by martinthomson** [comment]
Why not put the code in another file and run your validator over the file.  Then you can use the file import thingamy to pull the content of the file in.

**Comment by mnot** [comment]
Often they're just examples, a single line.

**Comment by mnot** [comment]
I'm now doing this with a completely separate program on both md and xml, so OBE.

**Comment by cabo** [comment]
A way to specify processing is very much planned, so I don't think this is totally OBE. But I've also had much success writing little tools that xpath through the XML and do some checks. There are also some builtin checks now, e.g. for json.
