### ISSUE TITLE
line_width

### ISSUE THREAD

**Issue by mnot** [cabo/kramdown-rfc#80]
Can we have an option (or default) to output XML that's wrapped to 78 characters?

The RPC apparently does this by hand (!), so giving them pre-wrapped XML will help reduce diffs.

This seems to the the [line_width option](https://kramdown.gettalong.org/options.html) to Kramdown.

**Comment by cabo** [comment]
The `line_width` option appears to be a parameter to the kramdown writer (which writes markdown).   This is not the one we are using when writing XML.  Given that the inner XML of a paragraph could have spaces in attribute values, wrapping it to a specific width is a bit of effort (and risk).

Note that you can pre-wrap your markdown and get nicely wrapped XML...

Would the RPC touch classically keyboarded text (new line for each sentence, sentences wrapped at column 72)?

**Comment by cabo** [comment]
It looks like they do.
The preptool then of course steamrolls over those neat line breaks.

**Comment by mnot** [comment]
Right, but preptool isn't run until after AUTH48.

**Comment by mnot** [comment]
Hm. Pre-wrapping the .md means that diffs change unnecessarily. I suppose we could ask them not to line-wrap the XML when they edit, but the problem is that they do that before interacting with the document authors for the first time.

**Comment by cabo** [comment]
No, this comment was just about the futility.
Note that the 78 columns includes the indent, which you would need to guess to input pre-formatted markdown.

**Comment by cabo** [comment]
Diffs are near optimal with classical keyboarding.

**Comment by mnot** [comment]
Maybe during the RFC Editor process, but during markdown editing on GitHub, no line wrapping seems to work best.

**Comment by cabo** [comment]
I think we'll need to discuss this on rfc-interest.

**Comment by mnot** [comment]
Good idea.

**Comment by cabo** [comment]
No line wrapping (i.e., no line ends) means that any change leads to a diff for the whole paragraph.
Classical keyboarding limits this to the sentence actually changed.
In particular if you can resist the temptation to reformat even sentences (unless the reach the margin of the TTY, in which case you just break that line).
That used to be second nature to me, but editors have made it too easy to accidentally reformat whole paragraphs...

**Comment by cabo** [comment]
(See how I wrote the above comment without even noticing?
But no sentence breaking needed here.)

**Comment by cabo** [comment]
Looking at rfc8746.notprepped.xml, there is one paragraph that is weirdly outdented ("Since one objective of..."), and even that is then filled up to column 78.   This is not really guessable...

**Comment by mnot** [comment]
If you add any significant text to a sentence that's line wrapped and then re-wrap, the diff is awful.

That's why the RPC XMLs have lines that are overly-long; they're manually inserting text and not rewrapping, to make the diff manageable.

Doing that throughout the editorial process is untenable; after a number of edits, the line wrapping is randomised.

**Comment by cabo** [comment]
Well, I stick with my statement that classical keyboarding (without obsessive rewrapping) leads to better diffs.

Anyway, I only find overly long lines in the notprepped file I'm looking at where there is XML that caused this.

Having a "preptool" that we use before handing over XML to the RPC sounds like a good idea!

**Comment by mnot** [comment]
Closing, as the RPC is no longer rewrapping XML.
